### PR TITLE
chore: conditionally create github release

### PR DESCRIPTION
**Pull request by ricky**
Also fix `body_path` parameter name.

### CODE REVIEW

**Review by jeversmann-shipstation — APPROVED** [review]

**Comment by ricky** [comment]
release deferred

**Review by lzhang — APPROVED** [review]

**Comment by ricky** [comment]
release deferred

**Comment by ricky** [comment]
release deferred

**Comment by ricky** [comment]
release deferred

**Comment by ricky** [comment]
release deferred

**Pull request merged**
