### PR TITLE
Update Init Infra

### PR DESCRIPTION
**Pull request by justin-shipstation**
There will now be a new step when you call `connect init --infra` you will be asked if this is a new beta app. If you answered yes we will use the new Dockerfile and Dockerfile.unittest.

Also added a helper to possibly catch a default integrations repo when initializing it.

### CODE REVIEW

**Comment by justin-shipstation** [comment]
increment minor

**Comment by mattburton** [comment]
Does the `beta` question serve any utility beyond this? As Josh [pointed out](https://github.com/ShipEngine/connect/pull/129#discussion_r638028407) on my PR that was doing this same thing maybe we should instead check if the new runtime is a dependency instead?

**Comment by justin-shipstation** [comment]
> Does the `beta` question serve any utility beyond this? As Josh [pointed out](https://github.com/ShipEngine/connect/pull/129#discussion_r638028407) on my PR that was doing this same thing maybe we should instead check if the new runtime is a dependency instead?

I went ahead and updated it based on your feedback.

**Review by mattburton — APPROVED** [review]
LGTM

**Pull request merged**
